import React from 'react';
import { Header, Footer } from '@/components/theme/LayoutComponents';

export default async function SinglePost({ params }: { params: Promise<{ slug: string }> }) {
    const { slug } = await params;

    return (
        <div style={{ minHeight: '100vh', display: 'flex', flexDirection: 'column' }}>
            <Header />
            <main style={{ flex: 1, maxWidth: '800px', margin: '0 auto', padding: '48px 24px', width: '100%' }}>
                <article>
                    <div style={{ marginBottom: '32px' }}>
                        <span style={{ backgroundColor: 'var(--pub-surface)', color: 'var(--pub-muted)', padding: '4px 8px', borderRadius: '4px', fontSize: '14px', marginBottom: '16px', display: 'inline-block' }}>Category</span>
                        <h1 style={{ fontSize: '36px', lineHeight: 1.2, margin: '8px 0 16px 0', color: 'var(--pub-heading)' }}>{slug.replace('-', ' ')}</h1>
                        <div style={{ color: 'var(--pub-muted)', fontSize: '15px', borderBottom: '1px solid var(--pub-border)', paddingBottom: '24px' }}>
                            👤 By Admin · Feb 28, 2026 · 5 min read
                        </div>
                    </div>

                    <div style={{ fontSize: '18px', lineHeight: 1.8, color: 'var(--pub-text)' }}>
                        <p style={{ marginBottom: '24px' }}>This is the main content area for the post. It will contain rich text generated by the classic editor.</p>
                        <p style={{ marginBottom: '24px' }}>Images, blockquotes, and headings will all be styled nicely here.</p>
                    </div>

                    <div style={{ marginTop: '48px', paddingTop: '24px', borderTop: '1px solid var(--pub-border)' }}>
                        <h3 style={{ fontSize: '18px', marginBottom: '12px' }}>Tags</h3>
                        <div style={{ display: 'flex', gap: '8px' }}>
                            <span style={{ backgroundColor: '#E5E7EB', padding: '4px 12px', borderRadius: '16px', fontSize: '13px' }}>news</span>
                            <span style={{ backgroundColor: '#E5E7EB', padding: '4px 12px', borderRadius: '16px', fontSize: '13px' }}>update</span>
                        </div>
                    </div>
                </article>
            </main>
            <Footer />
        </div>
    );
}
